### ISSUE TITLE
Message scans are not showing the last message in any one sub

### ISSUE THREAD

**Issue by dgets** [dgets/DOCshell#51]
When doing a forward scan the `last_msg` in the object is never displayed, only the ones prior to it.  My first place to peek on this issue would be where @ntwitch was mentioning that there is a disparity between pointers being utilized that start at a 0 index and those that start at 1 as the base.  Identify and compare the logic.

**Comment by dgets** [comment]
BTW: @ntwitch, if you could paste the commentary about those relevant pointers here I'm having a difficult time locating it.  Somehow my logs have gotten hosed from our chat, I think.  :P

**Comment by ntwitch** [comment]
**ntwitch:**  I think in a lot of places you need to be using *(base.total_msgs - 1)* instead of *base.last_msg*.
**ntwitch:**  Your pointer (*tp*, *tmpPtr*, *ptr*) is a 0-based index into the array of messages.
**ntwitch:**  *base.total_msgs* is a 1-based count of messages.
**ntwitch:**  *base.first_* and *last_msg* are message ID #s. These are numbered over all subforums in the base, they are not indexes.
**ntwitch:**  This is why your prompt shows 10 messages remaining when there is only one message in "Lobby".
**ntwitch:**  Because the message ID of the message in the Lobby is 10, and your pointer is at 0 (first message)
**ntwitch:**  So it shows 10-0 = 10 messages remaining.
**ntwitch:**  it should say 0 messages remaining, because you've already read the message at that point, and so *ptr* is 0, and *(base.total_msgs - 1)* is 0, and 0 - 0 = 0 messages remaining

**Comment by ntwitch** [comment]
Should be fixed as of 93352e1cd8599762e8fa0761b702bca5c1bb90e5

**Comment by ntwitch** [comment]
welp, not fixed.

**Comment by dgets** [comment]
Outstanding, dude.  :)

**Comment by ntwitch** [comment]
wow, that confused me for a minute. I didn't know your repo issue tracker would be watching my commits for references to issues :O

**Comment by dgets** [comment]
It depends on how you reference things.  :)  It's got some nice features to it.
