### ISSUE TITLE
cannot enter message: exception on hitting 'e' in a room

### ISSUE THREAD

**Issue by gordon-morehouse** [dgets/DOCshell#54]
I attempted to enter a message in Neutron Star> on the test system and received an exception. It then dumps me back to the room prompt.

```
[Neutron Star> msg #5 (3 remaining)] Read cmd -> Enter message

Ename: ReferenceError	Msg: addMsg is not defined	#: undefined
Got topegrpneutrons in user.cursub
Neutron Star>
```

**Comment by gordon-morehouse** [comment]
After dumping me to the room prompt, when I hit space again, it started reading the room from the beginning but I think this is a known bug.

**Comment by dgets** [comment]
So it appears at this point that the code actually is now calling `poast.addMsg()` correctly.  However, the `base` object that it is being passed from the `readCmd` menu doesn't seem to be defined, so it is still unable to write the message correctly.

**Comment by dgets** [comment]
Working on getting some debugging code in here and converting _dpoast.js_ to exception handling; looks like I overlooked this one file before since it was working 'perfectly' at the time I previously finished up on it.  Starting attempts at the debugging skeleton can be found here: https://github.com/dgets/DOCshell/commit/f80aa3a9b98eebbc04e53e8b0642aaa1e9598202.

I'm gonna give up for a little while again; my brain is too foggy this morning.  I'll hack at this more later.  @ntwitch, if you decide to take a stab at this, have no worries, I'm going to be checking carefully for the pulls and notifications before I touch anything else.

**Comment by dgets** [comment]
Should be fixed as of https://github.com/ntwitch/DOCshell/commit/7737abdc949bd5ae0e2bf90d2bd50ce51c790784 in pull https://github.com/dgets/DOCshell/pull/90
