### ISSUE TITLE
'?' menu at read prompt raises exception

### ISSUE THREAD

**Issue by gordon-morehouse** [dgets/DOCshell#74]
```
[Lobby> msg #0 (11 remaining)] Read cmd -> Exception reading new: ReferenceError: rcMenu is not defined
```

**Comment by dgets** [comment]
This is fixed as per https://github.com/dgets/DOCshell/commit/6120bea86b3c3a5e1852d060e567e78951819cb2.  This being said, there are still issues with the color codes that've gotten broken god knows where; when it comes across the color codes it shows a couple of `undefined` due to their inclusion in that menu, so this needs to be patched up as per a different issue.
